name: CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: [py39, py310, py311, py312, py313, py314, oldest]

    steps:
    - uses: actions/checkout@v4

    - uses: prefix-dev/setup-pixi@v0.10.0
      with:
        pixi-version: v0.72.1
        environments: ${{ matrix.env }}
        locked: true
        cache: true

    - name: Test with pytest
      run: pixi run -e ${{ matrix.env }} test
